version: "3.1"

services:
  db:
    image: postgres:10.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foosball
      POSTGRES_USER: foosball
      POSTGRES_PASSWORD: foosball
    volumes:
      - ./db-data:/var/lib/postgresql/data
