AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Le Bon Coin - Foosball

  GO test (Vincent Larrat)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: go1.x
    Timeout: 30

Resources:
  StoreGoalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: __binaries/scores/StoreGoal
      Handler: StoreGoal
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /goal
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_DIALECT: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_DIALECT}}'
          DB_HOST: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_HOST}}'
          DB_PORT: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_PORT}}'
          DB_NAME: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_NAME}}'
          DB_USERNAME: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_USERNAME}}'
          DB_PASSWORD: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_PASSWORD}}'
          DB_SSLMODE: '{{resolve:secretsmanager:LBC-Foosball-DB_parameters:SecretString:DB_SSLMODE}}'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StoreGoalAPI:
    Description: "API Gateway endpoint URL for Prod environment for StoreGoal function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/goal"
